const { ROLES } = require("./constants");

const PERMISSIONS = {
    LOGIN_ADMIN: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
    LOGIN_DRIVER: [ROLES.DRIVER],
    REGISTER_DRIVER: [ROLES.DRIVER],
    REQUEST_OTP: [ROLES.DRIVER],
    ADD_ADMIN: [ROLES.SUPER_ADMIN],
    ADD_DRIVER: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
    GET_ALL_DRIVERS: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
    ADD_LOCATION: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
    GET_ALL_LOCATIONS: [ROLES.DRIVER, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    ADD_VEHICLE: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
    GET_ALL_VEHICLES: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
    MANAGE_KYC: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
    CHECK_KYC: [ROLES.DRIVER],
    SUBMIT_KYC: [ROLES.DRIVER],
    GET_ALL_KYC_REQUESTS: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
};

module.exports = PERMISSIONS;
